[package]
name = "rustczt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustfft = "6.2.0"

[dev-dependencies]
assert2 = "0.3.13"
rand = "0.8.5"
